from django.shortcuts import render
import requests


def home_view(request):
    # first api request- random year
    response = requests.get('http://numbersapi.com/random/year?json')
    if response:
        random_number = response.json()
        number = random_number['number']
        response_text = random_number['text']

    # second api request- trivia on the number generated by the year in first request
    response2_url = "http://numbersapi.com/" + str(number) + "/trivia?json"
    response2 = requests.get(response2_url)
    if response2:
        random_fact = response2.json()
        response2_text = random_fact['text']

    # third api request- second random number trivia
    response3 = requests.get('http://numbersapi.com/random/trivia?json')
    if response3:
        random_number2 = response3.json()
        number2 = random_number2['number']
        response3_text = random_number2['text']

    # fourth api request- second random number maths
    response4_url = "http://numbersapi.com/" + str(number2) + "/math?json"
    response4 = requests.get(response4_url)
    if response4:
        maths_fact = response4.json()
        response4_text = maths_fact['text']

    print (random_number)
    print (random_fact)
    print (random_number2)
    print (maths_fact)

    context = {
        'number' : number,
        'response_text': response_text,
        'response2_text': response2_text,
        'number2': number2,
        'response3_text': response3_text,
        'response4_text': response4_text,
    }

    return render(request, 'home.html', context)
