from django.shortcuts import render
import requests


def home_view(request):
	# first api request- random year
	response = requests.get('http://numbersapi.com/random/year?json')
	random_number = response.json()
	number = random_number['number']
	response_text = random_number['text']

	# second api request- trivia on the number generated by the year in first request
	response2_url = "http://numbersapi.com/" + str(number) + "/trivia?json"
	response2 = requests.get(response2_url)
	random_fact = response2.json()
	response2_text = random_fact['text']

	context = {
		'number' : number,
		'response_text': response_text,
		'response2_text': response2_text,
	}

	return render(request, 'home.html', context)
